// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FortuneCookieController from "./fortune_cookie_controller"
application.register("fortune-cookie", FortuneCookieController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import InspireButtonController from "./inspire_button_controller"
application.register("inspire-button", InspireButtonController)

import StarRatingController from "./star_rating_controller"
application.register("star-rating", StarRatingController)

import WeeklyButtonController from "./weekly_button_controller"
application.register("weekly-button", WeeklyButtonController)

import ShakingController from "./shaking_controller"
application.register("shaking", ShakingController)
